<?php
// Database configuration - Generated by installer
return [
    'default' => 'mysql',
    'connections' => [
        'mysql' => [
            'type' => 'mysql',
            'hostname' => 'feiyu_mysql',
            'database' => 'feiyuadmin',
            'username' => 'root',
            'password' => 'root123456',
            'hostport' => '3306',
            'params' => [
                \PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4",
            ],
            'charset' => 'utf8mb4',
            'prefix' => 'sys_',
            'deploy' => 0,
            'rw_separate' => false,
            'master_num' => 1,
            'slave_no' => '',
            'fields_strict' => true,
            'break_reconnect' => false,
            'trigger_sql' => true,
            'fields_cache' => false,
        ],
    ],
];
